spring:
  redis:
#    host: localhost
#    port: 6379
#    uri: uri
    host:
    port:
    password:
  data:
    mongodb:
      uri:
      database:
      auto-index-creation: true
  mail:
    host: smtp.gmail.com # smtp.office365.com, smtp.mail.yahoo.com
    port: 587
    username: #
    password: # # this is the gmail app password, turn 2 step verification, deleted create a new one
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.journalappdemo.model # can contain
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: ;
      session:
        timeout:
          ms: 45000


server:
  port: 8080
  servlet:
    context-path:

#client:
#  id: