spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: book
    password: book

#    host: smtp.gmail.com
#    port: 465
#    username: 
#    password: 
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
#          ssl: # since using gmail thats why
#            enable: true
#            trust: "*"
        starttls:
          enable: true
    protocol: smtp
  security: # for keycloak
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"

application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 8640000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
#  mailing:
#    frontend:
#      activation-url: http://localhost:4200/activate-account

  file:
    upload:
      photos-output-path: ./uploads #

server:
  port: 8088